apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: guessgame
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: viniciusaraujo20/frontend:1.0.0
        ports:
          - containerPort: 80
