apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.backend.image }}
        ports:
          - containerPort: 5000
        env:
          - name: FLASK_APP
            value: "run.py"
          - name: FLASK_DB_TYPE
            value: "postgres"
          - name: FLASK_DB_USER
            value: "guessgame-user"
          - name: FLASK_DB_NAME
            value: "guessdb"
          - name: FLASK_DB_PASSWORD
            value: "rrp7OZV087T48V"
          - name: FLASK_DB_HOST
            value: "postgres"
          - name: FLASK_DB_PORT
            value: "5432"
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 500m
